name: Release
on:
  workflow_dispatch: 
    inputs:
      version: 
        description: Release version
        required: true
        type: boolean
jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"
      - run: yarn
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn test:ci
      - run: yarn build
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn build
      