name: Release
on:
  workflow_dispatch: 
    inputs:
      version: 
        description: Release version
        required: true
        type: string
jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "npm"
      - run: yarn
      - uses: actions/upload-artifact@master
        with:
          name: bauhaus
          path: ./
  test:
    name: Test
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: bauhaus
          path: ./
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn test:ci
  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: bauhaus
          path: ./
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn build
      