name: Release
on:
  workflow_dispatch: 
    inputs:
      version: 
        description: Release version
        required: true
        type: string
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn 
      - run: yarn test:ci
  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn
      - run: yarn build
      - run: npm version ${{ inputs.version }}
      - uses: actions/upload-artifact@master
        with:
          name: bauhaus
          path: ./build
      - run: git config --global user.email "demey.emmanuel@gmail.com"
      - run: npm ERR!   git config --global user.name "Emmanuel Demey"
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          message: "Create Release ${{ inputs.version }}"
          github_token: ${{ secrets.GITHUB_TOKEN }}
  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ inputs.version }}
          release_name: Release ${{ inputs.version }}
          draft: false
          prerelease: false
      